# Generated by Django 3.2.5 on 2021-07-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, unique=True)),
                ('html', models.TextField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('exception', models.BooleanField(default=False)),
                ('time_exceeded', models.BooleanField(default=False)),
            ],
        ),
    ]
