# Generated by Django 3.2.5 on 2021-07-30 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_rename_result_scraperentity_word_occurrences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scraperentity',
            name='exception',
        ),
        migrations.RemoveField(
            model_name='scraperentity',
            name='time_exceeded',
        ),
    ]
