# Generated by Django 3.2.5 on 2021-08-01 13:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_scraperentity_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperentity',
            name='last_refresh',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
