# Generated by Django 3.2.5 on 2021-08-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_scrape_wordcount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScraperEntity',
        ),
        migrations.AddField(
            model_name='scrape',
            name='error',
            field=models.BooleanField(default=False),
        ),
    ]
