# Generated by Django 3.2.5 on 2021-08-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0008_auto_20210802_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordcount',
            name='word',
            field=models.CharField(max_length=200),
        ),
    ]
