version: "3.9"

services:
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis:5.0
    container_name: redis

  django: &django
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    container_name: django
    restart: on-failure
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    command: >
      sh -c "sleep 5 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  celeryworker:
    <<: *django
    image: nate_local_celeryworker
    container_name: celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: celery -A backend.celery worker -l INFO

  frontend:
    build:
      context: .
      dockerfile: ./compose/frontend/Dockerfile
    container_name: frontend
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
